name: Build Dev APK

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-


      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'tools platform-tools platforms;android-34 build-tools;34.0.0 cmake;3.22.1 ndk;25.2.9519653'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure SDK and NDK paths
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ndk.dir=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> local.properties
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV


      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Rename APK with run number and timestamp
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          APK_PATH=$(ls ImguiDemoSdl/build/outputs/apk/debug/*.apk)
          NEW_NAME="ImguiDemoSdl-${BUILD_NUMBER}-${TIMESTAMP}.apk"
          mv "$APK_PATH" "ImguiDemoSdl/build/outputs/apk/debug/$NEW_NAME"
          echo "APK_NAME=$NEW_NAME" >> $GITHUB_ENV

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: ImguiDemoSdl/build/outputs/apk/debug/${{ env.APK_NAME }}
          compression-level: 0
